spamblock: Fix spamblock Akismet API request Error
API_ERROR: Akismet API failure: Missing required field: blog, ... requires a POST not a GET request